# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for chinadns-ng
LUCI_DESCRIPTION:=LuCI Support for chinadns-ng.
LUCI_DEPENDS:=+chinadns-ng
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-chinadns-ng
PKG_VERSION:=1
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

